---
env:
  contexts:
  - name: "Compass Authentication"
    urls:
    - "https://compass.gww.gov.bc.ca"
    includePaths:
    - "https://compass.gww.gov.bc.ca.*"
    excludePaths: []
    authentication:
      method: "browser"
      parameters:
        loginPageUrl: "https://compass.gww.gov.bc.ca"
        loginPageWait: 5
        browserId: "firefox"
      verification:
        method: "poll"
        loggedInRegex: "\\Q 200 OK\\E"
        loggedOutRegex: "\\Q 302 Moved Temporarily\\E"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: "https://compass.gww.gov.bc.ca/"
        pollPostData: ""
    sessionManagement:
      method: "headers"
      parameters:
        Cookie: "88b18f473ac9d856c21526a6326a1a8c=ba02c4305db8c4e0dbf02c26ee76aa79;\\ SMSESSION={%cookie:SMSESSION%}; FAILREASON=0; session=.eJx1j0ELgkAQhf_LniswJGjAgxiVpJaIFUWHzV1tTddw3RDF_56KkB26DMP7Hm_e1EjgNHFwSk2CAFn7zUo_mh6ajPR1lqe4aKnMOWRYMAG8BQKKADzdtkCZKb3CyDTsvSC5eNGAhYySn6huuhInHckRcJkkY-wd_ho8KgTLuMkJLdsqu9Oicp7-u5wbNg_vVqyS6nHZusY50kyqLuNI04bLvqA5wQVGUCPZ7oxQXgz51-_Ht6b5AFOdXbE.Zik8aw.Vux3c0yjhOzcs3F85rMm1ZRi2Ew;\\ _pk_ref.2.aad3=%5B%22%22%2C%22%22%2C1713978479%2C%22https%3A%2F%2Fsfs7.gov.bc.ca%2F%22%5D;\\ _pk_id.2.aad3=b2e07145849f4797.1713978479.; _pk_ses.2.aad3=1"
    technology:
      exclude: []
    users:
    - name: "${USERNAME}"
      credentials:
        password: "${PASSWORD}"
        username: "${USERNAME}"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: "Compass Authentication"
    user: "${USERNAME}"
    url: ""
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters:
    context: "Compass Authentication"
    user: "logdavis"
    url: ""
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 16
    inScopeOnly: true
    runOnlyIfModern: false
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    template: "traditional-pdf"
    reportDir: ""
    reportFile: "CompassScan"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  sites: []
  name: "report"
  type: "report"

