name: Zap scan on compass test

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP Automation Framework

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check URL Accessibility
      run: |
        curl -I https://compass.gww.gov.bc.ca  # Replace with your actual URL
        wget --spider -S https://compass.gww.gov.bc.ca

    - name: Replace secrets in compassTest.yaml
      run: |
        sed -i 's/\${USERNAME}/${{ secrets.USERNAME }}/g' zap/zap-config/compassTest.yaml
        sed -i 's/\${PASSWORD}/${{ secrets.PASSWORD }}/g' zap/zap-config/compassTest.yaml

    - name: Check Replacement Success
      run: |
        if grep -q '${USERNAME}' zap/zap-config/compassTest.yaml; then
          echo "Username placeholder not replaced."
          exit 1
        fi
        if grep -q '${PASSWORD}' zap/zap-config/compassTest.yaml; then
          echo "Password placeholder not replaced."
          exit 1
        fi
        echo "All placeholders replaced successfully."

    - name: Pull ZAP Docker Image
      run: docker pull softwaresecurityproject/zap-stable:latest
    
    - name: Run ZAP Automation Framework
      run: |
        docker run \
        -v ${{ github.workspace }}/zap/zap-config:/zap/zap-config \
        -v ${{ github.workspace }}/zap/reports:/zap/reports \
        softwaresecurityproject/zap-stable:latest bash -c "mkdir -p /zap/reports && zap.sh -cmd -autorun /zap/zap-config/compassTest.yaml"

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: ZAP-Report
        path: ${{ github.workspace }}/zap/reports/
