name: Zap scan on compass test

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP Automation Framework

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull ZAP Docker Image
      run: docker pull softwaresecurityproject/zap-stable:latest
    
    - name: Run ZAP Automation Framework
      run: |
        docker run \
        -v ${{ github.workspace }}/zap/zap-config:/zap/zap-config \
        -v ${{ github.workspace }}/zap/reports:/zap/reports \
        softwaresecurityproject/zap-stable:latest bash -c "mkdir -p /zap/reports && zap.sh -cmd -autorun /zap/zap-config/compassTest.yaml"

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: ZAP-Report
        path: ${{ github.workspace }}/zap/reports/
