name: Zap scan on compass test

on:
  push:
    branches:
      - main
jobs:
  zap_scan:
    runs-on: windows-latest
    name: Run ZAP Automation Framework

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace secrets in compassTest.yaml
      shell: pwsh
      run: |
        (Get-Content zap/zap-config/compassTest.yaml) -replace '\${USERNAME}', '${{ secrets.USERNAME }}' | Set-Content zap/zap-config/compassTest.yaml
        (Get-Content zap/zap-config/compassTest.yaml) -replace '\${PASSWORD}', '${{ secrets.PASSWORD }}' | Set-Content zap/zap-config/compassTest.yaml

    - name: Run ZAP Automation Framework
      uses: docker://softwaresecurityproject/zap-stable:latest
      with:
        args: /zap/zap.sh -cmd -autorun /zap/zap-config/compassTest.yaml
      env:
        ZAP_CONFIG_DIR: ${{ github.workspace }}/zap

    - name: Setup ZAP Configuration
      run: |
        mkdir -p /zap/zap-config
        cp -r $ZAP_CONFIG_DIR/* /zap/zap-config/
      shell: pwsh
